### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by DTL819** [Lawaxi/ShitBoyJuJuAddon#1]
作者您好，今天尝试配置了一下，没弄成功，能请教一下吗

**Comment by DTL819** [comment]
口袋48机器人可以使用，但是这个不大行

**Comment by Lawaxi** [comment]
发送报错信息

**Comment by DTL819** [comment]
2023-06-18 21:15:18 E/ShitBoyJuJuAddon: java.lang.NullPointerException
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Unknown Source)
        at java.base/java.util.Arrays$ArrayList.<init>(Unknown Source)
        at java.base/java.util.Arrays.asList(Unknown Source)
        at ShitBoyJuJuAddon-0.1.1.mirai2.jar//net.lawaxi.jujuaddon.config.init(config.java:36)
        at ShitBoyJuJuAddon-0.1.1.mirai2.jar//net.lawaxi.jujuaddon.config.<init>(config.java:30)
        at ShitBoyJuJuAddon-0.1.1.mirai2.jar//net.lawaxi.jujuaddon.ShitBoyJuJuAddon.onEnable(ShitBoyJuJuAddon.java:35)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:232)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:305)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:181)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:347)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:496)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)

**Comment by DTL819** [comment]
同时谢谢大佬提供脚本使用！！！

**Comment by Lawaxi** [comment]
最新版已修复
https://github.com/Lawaxi/ShitBoyJuJuAddon/releases/tag/0.1.2
