### ISSUE TITLE
启动时日志报错

### ISSUE THREAD

**Issue by onlyzqy** [Lawaxi/ShitBoyJuJuAddon#4]
使用shitboy-0.1.10和jujuaddon-0.1.2-test4，每次启动时会有如下日志错误信息

E/ShitBoyJuJuAddon: Exception in coroutine Plugin net.lawaxi.shitboyjja of ShitBoyJuJuAddon
cn.hutool.core.exceptions.UtilException: Scheduler has been started, please stop it first!
	at shitboy-0.1.10.mirai2.jar[shared]//cn.hutool.cron.CronUtil.start(CronUtil.java:153)
	at shitboy-0.1.10.mirai2.jar[shared]//cn.hutool.cron.CronUtil.start(CronUtil.java:143)
	at ShitBoyJuJuAddon-0.1.2-test4.mirai2.jar//net.lawaxi.jujuaddon.ShitBoyJuJuAddon.listenBroadcast(ShitBoyJuJuAddon.java:67)
	at ShitBoyJuJuAddon-0.1.2-test4.mirai2.jar//net.lawaxi.jujuaddon.ShitBoyJuJuAddon.lambda$onEnable$0(ShitBoyJuJuAddon.java:46)
	at net.mamoe.mirai.event.EventChannel$subscribeOnce$2$1.invoke(EventChannel.kt:654)
	at net.mamoe.mirai.event.EventChannel$subscribeOnce$2$1.invoke(EventChannel.kt:654)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Lawaxi** [comment]
用签名服务器登陆造成的问题，过几天会修复，不过目前使用上完全不受影响，可以忽略报错信息

**Comment by Lawaxi** [comment]
已更新，可以尝试0.1.2-test5
